export {
  CANONICAL_SECTION_KEYS,
  DEFAULT_SECTION_HEADINGS,
  DEFAULT_SECTION_ORDER,
  SECTION_HEADING_ALIASES,
  TEMPLATE_SECTION_PRIORITIES,
  canonicalizeSectionId,
  createDefaultSectionConfig,
  getRecommendedSectionOrder,
  getSectionOrder,
  isCanonicalSectionKey,
  isSectionPresent,
  normalizeSectionConfig,
  resolveSectionHeading,
} from './sectionEngine';
