import { Document as DocxDocument, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, convertInchesToTwip } from 'docx';
import { ResumeData } from '../types';

function buildDocx(resume: ResumeData): DocxDocument {
  const details = resume.personalDetails;
  const children: (Paragraph | Table)[] = [];

  // Name header
  children.push(new Paragraph({
    children: [new TextRun({ text: details.fullName || 'Resume', bold: true, size: 36, font: 'Inter' })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 100 },
  }));

  // Title
  if (details.professionalTitle) {
    children.push(new Paragraph({
      children: [new TextRun({ text: details.professionalTitle, size: 22, color: '6c5ce7', font: 'Inter' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 },
    }));
  }

  // Contact row
  const contactParts = [details.email, details.phone, details.location].filter(Boolean);
  if (contactParts.length > 0) {
    children.push(new Paragraph({
      children: [new TextRun({ text: contactParts.join(' · '), size: 18, color: '555555', font: 'Inter' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }));
  }

  // Links
  const links = [details.linkedin, details.github, details.website].filter(Boolean);
  if (links.length > 0) {
    children.push(new Paragraph({
      children: [new TextRun({ text: links.join(' · '), size: 16, color: '6c5ce7', font: 'Inter' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }));
  }

  // Helper: add section heading
  const addHeading = (text: string) => {
    children.push(new Paragraph({
      children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 20, color: '1a1a2e', font: 'Inter' })],
      spacing: { before: 280, after: 120 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '6c5ce7', space: 4 } },
    }));
  };

  // Helper: add description text
  const addBody = (text: string) => {
    if (!text.trim()) return;
    text.split('\n').filter(Boolean).forEach(line => {
      children.push(new Paragraph({
        children: [new TextRun({ text: line.replace(/^[-•]\s*/, ''), size: 20, color: '333333', font: 'Inter' })],
        spacing: { after: 60 },
        indent: { left: convertInchesToTwip(0.25) },
      }));
    });
  };

  const addEntry = (title: string, subtitle: string, date: string) => {
    const runs: TextRun[] = [new TextRun({ text: title, bold: true, size: 20, font: 'Inter' })];
    if (subtitle) runs.push(new TextRun({ text: ` — ${subtitle}`, size: 18, color: '6c5ce7', font: 'Inter' }));
    children.push(new Paragraph({
      children: runs,
      spacing: { before: 100, after: 20 },
    }));
    if (date) {
      children.push(new Paragraph({
        children: [new TextRun({ text: date, size: 16, color: '888888', font: 'Inter' })],
        spacing: { after: 60 },
      }));
    }
  };

  // Summary
  if (resume.summary) {
    addHeading('Summary');
    addBody(resume.summary);
  }

  // Experience
  if (resume.experience.length > 0) {
    addHeading('Experience');
    resume.experience.forEach(exp => {
      addEntry(exp.title, exp.company, `${exp.startDate} — ${exp.endDate}`);
      addBody(exp.description);
    });
  }

  // Education
  if (resume.education.length > 0) {
    addHeading('Education');
    resume.education.forEach(edu => {
      addEntry(edu.degree, edu.institution, `${edu.startDate} — ${edu.endDate}`);
      if (edu.description) addBody(edu.description);
    });
  }

  // Projects
  if (resume.projects.length > 0) {
    addHeading('Projects');
    resume.projects.forEach(proj => {
      addEntry(proj.name, proj.technologies, [proj.startDate, proj.endDate].filter(Boolean).join(' — '));
      if (proj.description) addBody(proj.description);
    });
  }

  // Skills
  const skillEntries = Object.entries(resume.skills)
    .filter(([, values]) => values.length > 0)
    .map(([key, values]) => `${key.replace(/([A-Z])/g, ' $1')}: ${values.join(', ')}`);
  if (skillEntries.length > 0) {
    addHeading('Skills');
    skillEntries.forEach(skill => addBody(skill));
  }

  // Certifications
  if (resume.certifications.length > 0) {
    addHeading('Certifications');
    resume.certifications.forEach(cert => {
      addEntry(cert.name, cert.issuer, cert.date);
    });
  }

  // Achievements
  if (resume.achievements.length > 0) {
    addHeading('Achievements');
    resume.achievements.forEach(ach => addBody(ach));
  }

  // Languages
  if (resume.languages.length > 0) {
    addHeading('Languages');
    addBody(resume.languages.join(', '));
  }

  return new DocxDocument({
    title: details.fullName || 'Resume',
    description: 'Professional resume generated by Forge Resume',
    styles: {},
    sections: [{ children }],
  });
}

export async function createResumeDocx(resume: ResumeData): Promise<Blob> {
  const doc = buildDocx(resume);
  const buffer = await Packer.toBuffer(doc);
  return new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
}

export async function createResumePng(pdfBlob: Blob): Promise<Blob> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url).href;
  const document = await pdfjs.getDocument({ data: new Uint8Array(await pdfBlob.arrayBuffer()) }).promise;
  const rendered: HTMLCanvasElement[] = [];
  for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) {
    const page = await document.getPage(pageNumber);
    const viewport = page.getViewport({ scale: 2 });
    const canvas = window.document.createElement('canvas');
    const context = canvas.getContext('2d');
    if (!context) throw new Error('image_export_failed');
    canvas.width = Math.ceil(viewport.width);
    canvas.height = Math.ceil(viewport.height);
    await page.render({ canvas, canvasContext: context, viewport }).promise;
    rendered.push(canvas);
  }
  const gap = document.numPages > 1 ? 24 : 0;
  const output = window.document.createElement('canvas');
  output.width = Math.max(...rendered.map(canvas => canvas.width));
  output.height = rendered.reduce((sum, canvas) => sum + canvas.height, 0) + gap * Math.max(0, rendered.length - 1);
  const context = output.getContext('2d');
  if (!context) throw new Error('image_export_failed');
  context.fillStyle = '#ffffff';
  context.fillRect(0, 0, output.width, output.height);
  let y = 0;
  rendered.forEach(canvas => {
    context.drawImage(canvas, Math.round((output.width - canvas.width) / 2), y);
    y += canvas.height + gap;
  });
  const blob = await new Promise<Blob | null>(resolve => output.toBlob(resolve, 'image/png'));
  if (!blob) throw new Error('image_export_failed');
  return blob;
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1_000);
}
